#!/usr/bin/perl -w

use SNMP_Session;
use SNMP_util;

my $routes_file = 'test/CheckRoutes.txt';

my $router = "swiTIX.switch.ch";
my $target = "hctiws\@$router";
my $neighbor = "194.42.48.7";
my $neighbor_as = 8404;

snmpQueue_MIB_File ('/usr/local/share/snmp/mibs/BGP4-MIB.my');

my ($prefix, $preflen, @octets, $binp);
open (SRC, $routes_file) or die "open $routes_file: $!";
while (<SRC>) {
    if (/^.  *([0-9.]+)\/([0-9]+)\s/) {
	$prefix = $1;
	$preflen = $2;
    } elsif (/^.  *([0-9.]+)\s/) {
	$prefix = $1;
	$preflen = undef;
    } else {
	next;
    }
    $binp = pack ("CCCC", (@octets = split ('\.', $prefix)));
    if (! defined $preflen) {
	if ($octets[0] < 128) {
	    $preflen = 8;
	} elsif ($octets[0] < 192) {
	    $preflen = 16;
	} elsif ($octets[0] < 224) {
	    $preflen = 24;
	} else {
	    die "Weird address $prefix";
	}
    }
    {
	my $best_neighbor;
	snmpmaptable ($target, sub (@) {
	    my ($index, $best) = @_;
	    if ($best == 2) {
		$best_neighbor = $index;
	    }
	},
		      'bgp4PathAttrBest.'.$prefix.'.'.$preflen);
	if (defined $best_neighbor) {
	    if ($best_neighbor ne $neighbor) {
		warn "$prefix/$preflen: Unexpected best-path neighbor $best_neighbor.\n"
	    }
	} else {
	    warn "$prefix/$preflen: No best path found.\n"
	}
    }
}
close (SRC);
