#!/usr/local/bin/perl -w

use strict;

require 5;

use SNMP_Session;
use BER;

my $host = shift @ARGV || die;
my $community = shift @ARGV || die;

my $sysDescr = encode_oid (1,3,6,1,2,1,1,1,0);

my $session = SNMP_Session->open ($host, $community, 161)
    || die "Cannot open SNMP session";
my @oids = ($sysDescr);
$session->send_query ($session->encode_get_request (@oids));
while ($session->wait_for_response ($session->timeout)) {
    my($response_length);

    $response_length
	= $session->receive_response_3 (SNMP_Session::get_response, \@oids, 0);
    if ($response_length) {
	my $response = $session->pdu_buffer;
	my ($binding, $bindings, $oid, $value);
	eval {
	    ($bindings) = $session->decode_get_response ($response);

	    while ($bindings ne '') {
		($binding,$bindings) = decode_sequence ($bindings);
		($oid,$value) = decode_by_template ($binding, "%O%@");
		##print $pretty_oids{$oid}," => ",
		{
		    my $string = pretty_print ($value);
		    local $* = 1;
		    $string =~ s/\n/\\n/g;
		    $string =~ s/\r/\\r/g;
		    print "sysDescr.0: ", $string, "\n";
		}
	    }
	}
    }
}

$session->close ();
1;
